/*
 * File: app/view/ui/MyTabPanel.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ui.MyTabPanel', {
    extend: 'Ext.tab.Panel',

    config: {
        tabBar: {
            docked: 'top'
        },
        items: [
            {
                xtype: 'container',
                title: 'Profile',
                items: [
                    {
                        xtype: 'formpanel'
                    },
                    {
                        xtype: 'textfield',
                        label: 'Name'
                    },
                    {
                        xtype: 'sliderfield',
                        label: 'Weight'
                    },
                    {
                        xtype: 'sliderfield',
                        label: 'Height'
                    },
                    {
                        xtype: 'fieldset',
                        docked: 'bottom',
                        title: 'BMI',
                        items: [
                            {
                                xtype: 'textfield',
                                label: 3.1
                            }
                        ]
                    },
                    {
                        xtype: 'button',
                        docked: 'bottom',
                        text: 'Update'
                    }
                ]
            },
            {
                xtype: 'container',
                ui: '',
                layout: {
                    type: 'card'
                },
                title: 'Activity',
                items: [
                    {
                        xtype: 'toolbar',
                        docked: 'bottom',
                        layout: {
                            align: 'center',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                ui: 'action',
                                text: 'Foods'
                            },
                            {
                                xtype: 'segmentedbutton'
                            },
                            {
                                xtype: 'button',
                                ui: 'action',
                                text: 'Workout'
                            }
                        ]
                    },
                    {
                        xtype: 'list',
                        itemTpl: [
                            '<div>List Item {string}</div>'
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'Reports',
                items: [
                    {
                        xtype: 'button',
                        itemId: 'mybutton',
                        ui: 'decline',
                        text: 'Weekly '
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMybuttonRelease',
                event: 'release',
                delegate: '#mybutton'
            }
        ]
    },

    onMybuttonRelease: function(button, e, options) {
        
    }

});